# name: Firebase CI

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 16.x

#       - name: Install Yarn
#         run: npm install -g yarn

#       - name: yarn install, build, and test
#         run: |
#           yarn install
#           yarn build

#       - name: Archive Build
#         uses: actions/upload-artifact@v2
#         with:
#           name: build
#           path: build

#   deploy:
#     name: Deploy
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Download Build
#         uses: actions/download-artifact@v2
#         with:
#           name: build
#           path: build

#       - name: Debug Secrets
#         run: |
#           echo "FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}"
#           echo "FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}"
#           echo "FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}"
#       - name: Install Firebase CLI
#         run: yarn global add firebase-tools@latest
#       - name: Deploy to Firebase Hosting
#         run: firebase deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#           REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
#           REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
#           REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
#           REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
#           REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
#           REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
#           REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

name: Firebase CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Firebase CLI
        run: yarn global add firebase-tools@latest

      - name: Authenticate with Firebase
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > $HOME/firebase-service-account.json
          firebase login:ci --no-localhost --token "$FIREBASE_TOKEN" < $HOME/firebase-service-account.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DALIASARTWEBSITE }}

      - name: Build and Deploy to Firebase Hosting
        run: |
          yarn install
          yarn build
          firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
